lenong/LeongGoodApp/urls.py
from django.conf.urls import url
from LeongGoodApp import views as v
urlpatterns =[
    url(r'detail/(\d+)/',v.detail,name='detail'),
    url(r'test/',v.test1),
    url(r'list/(?P<fkey>\d+)/(?P<pindex>\d+)',v.list,name='fruite'),
    url(r'index',v.index,name='index'),
    url(r'hehehe/(\d+)',v.heheda,name='hehehe'),
    url(r'order/',v.user_order,name='user_order'),
    url(r'cart',v.cart,name='cart'),
    url(r'place_order',v.place_order,name='place_order')


]

lenong/lenong/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from lenongapp import urls as user_urls
from LeongGoodApp import  urls as good_url
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'user/',include(user_urls,namespace='user')),
    url(r'tinymce/',include('tinymce.urls')),
    url(r'goods/',include(good_url,namespace='goods')),
    url(r'ckeditor/',include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

lenong/lenongapp/urls.py
from django.conf.urls import url
from lenongapp import views as v
urlpatterns =[
    url(r'register',v.index,name='register'),
    url(r'ok/',v.useri,name='ok'),
    url(r'login_handle/',v.login_handle,name='login_handle'),
    url(r'login/',v.login,name='login'),
    url(r'userinfo/',v.user_info,name='user_info'),
    url(r'site/',v.user_site,name='user_site'),
    url(r'site_handle/',v.site_handle,name='site_handle')
]

lenong/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title%}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/register.js"></script>
    {% block head %}{% endblock %}
</head>
<body>
{% block body %}{% endblock %}

{% block footer %}{% endblock %}
</body>
</html>

lenong/templates/base2.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}
	基类模板
	{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
    {% block head %}

    {% endblock %}
</head>
<body>
{% block header %}
<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到乐农优选!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'goods:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>


{% endblock %}
{% block body %}

{% endblock %}
{% block footer %}
<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 乐农优选技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<script type="text/javascript" src="/static/js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}
</body>
</html>

lenong/templates/cart.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="author" content="http://www.softwhy.com/" />
	<title>乐农优选-购物车</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script src="https://cdn.bootcss.com/jquery/1.11.1/jquery.js"></script>
    <script>
function jisuan(obj){
  var total=0;
  var fruits=document.getElementsByName("fruit");
  for (var index = 0; index < fruits.length; index++) {
    if (fruits[index].checked) {
      total += parseFloat(fruits[index].value);
    }
  }
  myspan.innerHTML=total+"元";
}
window.onload=function(){
  var obox=document.getElementById("box");
  var inputs=obox.getElementsByTagName("input");
  for (var index = 0; index < inputs.length; index++) {
    inputs[index].onclick = function () {
      jisuan(this)
    }
  }
}
</script>

    <script>
/* 删除*/
   function cart_del(cart_id){
   		del=confirm('确定要删除吗？');
   		if(del){
   			$.get('/cart/delete'+cart_id+'/',function(data){
{#   				if(data.ok==1){#}
                $('ul').remove('#'+cart_id);
                $('.total_count1').text(data.count)
                $('.countGood').text(data.count)
                calculateTotal();
{#   				}#}

   			});
   		}
   }

 $(function(){

 /* 计算价格数量函数*/
   function calculateTotal(){
     /* 小计价格*/
     var sumTotal = 0;
     var countGood = 0;
     $('.col07').each(function(){
		//获取数量
       count = $(this).prev().find('input').val();
		//获取单价
       price = $(this).prev().prev().text();
		//小计
       total01 = parseInt(count) * parseFloat(price);
       $(this).text(total01.toFixed(2));

       if($(this).siblings('.col01').children('input').prop('checked')){
         sumTotal += parseFloat(total01.toFixed(2));
         countGood += 1;
       }

     });
     /* 总计价格*/
     $('#sumtotal').text(sumTotal);
     $('.countGood').text(countGood);
   };

   calculateTotal();


	 /* 勾选总开关*/
   $('#checkToggle').click(function(){
     state = $(this).prop('checked');
     $('.checkbox').prop({'checked':state});
     calculateTotal();
   });

   /* 单个勾选开关*/
   $('.checkbox').change(function(){
     checked();
     calculateTotal();
   });
   function checked(){
     if($('input[name=checked]:checked').length == $('input[name=checked]').length){
       $('#checkToggle').prop({'checked':true});
     }
     else{
       $('#checkToggle').prop({'checked':false});
     };
   };



   /* 新增*/
   $('.add').click(function(){
     txt = $(this).next();
     if (txt.val()<100){
       txt.val(parseFloat(txt.val())+1).blur();
     };
     goodid = $(this).parents('.cart_list_td').attr('id');
     count = $(this).val();
     url = '/cart/edit'+goodid+'_'+count+'/';
     $.get(url,function(data){
       if(data.status=1){
       }
     });
     	calculateTotal();
   });

   /* 减少*/
   $('.minus').click(function(){
     txt = $(this).prev();
     if (txt.val()>1){
       txt.val(parseFloat(txt.val())-1).blur();
     };
     goodid = $(this).parents('.cart_list_td').attr('id');
     count = $(this).val();
     url = '/cart/edit'+goodid+'_'+count+'/';
     $.get(url,function(data){
       if(data.status=1){
       }
     });
     calculateTotal();
   });

   /* 手动修改*/
   $('.num_show').blur(function(){
     count = $(this).val();
     if (count<=0){
       $(this).val(1);
     }
     else if(count>=100){
       $(this).val(99);
     }
     goodid = $(this).parents('.cart_list_td').attr('id');
     count = $(this).val();
     url = '/cart/edit'+goodid+'_'+count+'/';
     $.get(url,function(data){
     });
     calculateTotal();
   });
 })
 </script>

</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到乐农优选!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'goods:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="total_count">全部商品<em>2</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form action="" method="get" id="checkboxform">

    <ul class="cart_list_td clearfix">
    <ul id="box">
        {% for foo in a %}
        <li class="col01">

        <input type="checkbox" name="fruit"  class="checkbox" value="{{ foo.gprice }}">
		<li class="col02"><img src="/static/images/goods/goods012.jpg"></li>
		<li class="col03">{{ foo.gtitle }}<br><em>{{ foo.gprice }}/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">{{ foo.gprice }}</li>
		<li class="col06">
			<div class="num_add">
               <a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="{{foo.id}}">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07" class="price">{{ foo.gprice }}</li>
		<li class="col08"><a href="javascript:cart_del({{cart.id}});">删除</a></li>
        {% endfor %}
    </ul>
	</ul>

</form>



	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em><span id="myspan">0元</span></em><br>共计<b>2</b>件商品</li>
		<li class="col04"><a href="place_order.html">去结算</a></li>
	</ul>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 乐农优选信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>


</body>
</html>

lenong/templates/detail.html
{% extends 'base2.html' %}
{% block head %}
<script src="https://cdn.bootcss.com/jquery/1.11.1/jquery.js"></script>
{% endblock %}
{% block body %}
<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="{% url 'goods:fruite' 2 1 %}" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:fruite' 2 1 %}">新鲜水果</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl">{{ a.gpic|safe }}</div>

		<div class="goods_detail_list fr">
			<h3>{{ a.gtitle }}</h3>
			<p>草莓浆果柔软多汁，味美爽口，适合速冻保鲜贮藏。草莓速冻后，可以保持原有的色、香、味，既便于贮藏，又便于外销。</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ a.gprice }}</em></span>
				<span class="show_unit">单  位：{{ a.gunit }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl"> <ul id="lists">
       <li>

          <input type="text" class="num_show fl" value="1" id="in1">
					<span class="add fr" id="p">+</span>
					<span class="minus fr" id="p1">-</span>

       </li>

   </ul>
				</div>
			</div>
			<div class="total" >总价：<span id="price">2元</span></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="{% url 'goods:hehehe' a.id %} }" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="/static/images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="/static/images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ a.gjianjie }}</dd>
				</dl>
			</div>

		</div>
	</div>

    <script>

     var a = document.getElementById('p')
     var c = document.getElementById('in1')
     var data = {{ a.gprice|safe }}
    var price = document.getElementById('price')
      $('#p').click(function () {
    c.value = parseInt(c.value)+parseInt(1)
    price.innerText = parseFloat(data)*parseFloat(c.value)

})

      $('#p1').click(function () {
    c.value = parseInt(c.value)-parseInt(1)
price.innerText = parseFloat(data)*parseFloat(c.value)

    })








</script>
{% endblock %}

lenong/templates/user_center_info.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}
	乐农优选-用户中心
	{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到乐农优选!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'goods:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% block body %}
<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_info' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'goods:user_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:user_site' %}" >· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ a.uname }}</li>
							<li><span>联系方式：</span>{{ a.uphone }}</li>
							<li><span>联系地址：</span>{{ a.uaddress }}</li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				<li>
					<a href="detail.html"><img src="/static/images/goods/goods003.jpg"></a>
					<h4><a href="detail.html">大兴大棚草莓</a></h4>
					<div class="operate">
						<span class="prize">￥16.80</span>
						<span class="unit">16.80/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="/static/images/goods/goods004.jpg"></a>
					<h4><a href="#">吐鲁番梨光杏</a></h4>
					<div class="operate">
						<span class="prize">￥5.50</span>
						<span class="unit">5.50/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="/static/images/goods/goods005.jpg"></a>
					<h4><a href="#">黄肉桃</a></h4>
					<div class="operate">
						<span class="prize">￥10.00</span>
						<span class="unit">10.00/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="/static/images/goods/goods006.jpg"></a>
					<h4><a href="#">进口西梅</a></h4>
					<div class="operate">
						<span class="prize">￥28.80</span>
						<span class="unit">28.8/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>

				<li>
					<a href="#"><img src="/static/images/goods/goods007.jpg"></a>
					<h4><a href="#">香梨</a></h4>
					<div class="operate">
						<span class="prize">￥6.45</span>
						<span class="unit">6.45/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
			</ul>
		</div>
		</div>
	</div>
{% endblock %}




	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 乐农优选信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>

lenong/templates/user_center_order.html
{% extends 'user_center_info.html' %}
{% block body %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'goods:user_order' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'user:user_site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">未支付</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for foo in b %}
                                <ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/images/goods02.jpg"></li>
									<li class="col02">{{ foo.gtitle }}<em>11.80元/500g</em></li>
									<li class="col03">1</li>
									<li class="col04">11.80元</li>
								</ul>
                                {% endfor %}



							</td>
							<td width="15%">33.60元</td>
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>

				<ul class="order_list_th w978 clearfix">
					<li class="col01">2016-8-21 17:36:24</li>
					<li class="col02">订单号：56872934</li>
					<li class="col02 stress">已支付</li>
				</ul>
				<table class="order_list_table w980">
					<tbody>

                    <tr>
							<td width="55%">
                                {% for a in a %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/images/goods02.jpg"></li>
									<li class="col02">{{ a.gtitle }}<em>11.80元/500g</em></li>
									<li class="col03">1</li>
									<li class="col04">11.80元</li>
								</ul>
								{% endfor %}
							</td>
							<td width="15%">33.60元</td>
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
						</tr>


					</tbody>
				</table>

				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>
{% endblock %}





lenong/templates/user_center_site.html
{% extends 'user_center_info.html' %}

{% block body %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user_info' %}">· 个人信息</a></li>
				<li><a href="{% url 'goods:user_order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:user_site' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ a.uaddress }}</dd>
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="{% url 'user:site_handle' %}" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="name">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="post1">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="shouji">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock %}